version: "3.8"
services: 
    app:
        build:
          context: .
          dockerfile: dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
          - ./:/var/www
        networks: 
            - backend
    nginx_laravel:
        image: nginx:latest
        container_name: nginx_laravel
        restart: always
        volumes:
            - .:/var/www/
            - ./nginx/:/etc/nginx/conf.d/
        ports: 
            - 8000:80
        networks: 
            - backend
    mysql_laravel:
        platform: linux/x86_64
        image: mysql
        tty: true
        container_name: mysql_laravel
        restart: always
        ports:
            - 3307:3306
        environment: 
            MYSQL_DATABASE: laravel
            MYSQL_USER: username
            MYSQL_PASSWORD: password
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes: 
            - db:/var/lib/mysql
        networks: 
            - backend
networks: 
    backend:
        driver: bridge
volumes: 
    db: